apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-runtime-config
data:
  runtime-config.json: |
    {
      "bffBasePath": "/bff/v1",
      "acceptedBffContractRange": "${ACCEPTED_BFF_CONTRACT_RANGE}",
      "environment": "${ENVIRONMENT}"
    }
