apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-migrator
  namespace: career-migrations
  annotations:
    azure.workload.identity/client-id: ${MIGRATION_CLIENT_ID}
    knowledgebase.io/postgresql-role: core_migrator_ddl_backfill
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: core-migration
automountServiceAccountToken: false
