apiVersion: v1
kind: ServiceAccount
metadata:
  name: alb-controller-sa
  namespace: azure-alb-system
  annotations:
    azure.workload.identity/client-id: "${ALB_CONTROLLER_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: true
