#!/usr/bin/env python3
"""Generate small, deterministic runtime indexes from authoritative contracts."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
FEATURE = ROOT / "specs/003-develop-ui/contracts"
BFF = FEATURE / "bff-api-v1.openapi.yaml"
CORE = FEATURE / "core-api-v1.openapi.yaml"
CATALOG = FEATURE / "supported-guidance-topics-v1.yaml"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def operations(path: Path) -> list[dict[str, str]]:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    result: list[dict[str, str]] = []
    for route, path_item in document["paths"].items():
        for method, operation in path_item.items():
            if method.lower() in {"get", "put", "post", "delete", "patch"}:
                result.append({"operationId": operation["operationId"], "method": method.upper(), "path": route})
    return result


def ts_index(name: str, source: Path, entries: list[dict[str, str]], extras: str = "") -> str:
    constant = name.upper()
    encoded = json.dumps(entries, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/ci/generate_contracts.py. Do not edit.\n"
        f'export const {constant}_CONTRACT_DIGEST = "{digest(source)}" as const;\n'
        f"export const {constant}_OPERATIONS = {encoded} as const;\n"
        f"export type {name.title().replace('_', '')}OperationId = typeof {constant}_OPERATIONS[number][\"operationId\"];\n"
        + extras
    )


def generated_files() -> dict[Path, str]:
    bff_ops = operations(BFF)
    core_ops = operations(CORE)
    catalog = yaml.safe_load(CATALOG.read_text(encoding="utf-8"))
    topics = catalog["topics"]
    ui_extra = """

export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  code: string;
  detail?: string;
  correlationId?: string;
  errors?: Record<string, string[]>;
}

export interface CapabilityMetadata {
  contractVersion: string;
  catalogVersion: string;
  status: "compatible" | "read_only";
  generatedAt: string;
  supportedContractVersions: string[];
  supportedMutations: string[];
}

export interface BrowserSession {
  authenticated: boolean;
  employee?: { displayName: string };
  idleExpiresAt?: string;
  absoluteExpiresAt?: string;
  csrfToken?: string;
}
"""
    topic_json = json.dumps(topics, indent=2, ensure_ascii=False)
    topic_ts = (
        "// Generated by scripts/ci/generate_contracts.py. Do not edit.\n"
        "export type GuidanceTopicState = \"active\" | \"unavailable\" | \"retired\";\n"
        f'export const GUIDANCE_CATALOG_VERSION = "{catalog["catalog_version"]}" as const;\n'
        f'export const GUIDANCE_CATALOG_DIGEST = "{digest(CATALOG)}" as const;\n'
        f"export const GUIDANCE_TOPICS = {topic_json} as const;\n"
        "export type GuidanceTopic = typeof GUIDANCE_TOPICS[number];\n"
    )
    py_models = (
        '"""Generated core OpenAPI operation inventory. Do not edit."""\n\n'
        f'CORE_CONTRACT_DIGEST = "{digest(CORE)}"\n'
        f"CORE_OPERATIONS = {repr(tuple(entry['operationId'] for entry in core_ops))}\n"
    )
    py_validation = '''"""Runtime operation-registration validation against generated inventory."""\n\nfrom .core_api_models import CORE_OPERATIONS\n\n\ndef validate_registered_operations(operation_ids: set[str]) -> None:\n    unknown = operation_ids - set(CORE_OPERATIONS)\n    if unknown:\n        raise RuntimeError(f"Unknown core operation registrations: {sorted(unknown)}")\n'''
    return {
        ROOT / "ui/src/contracts/bff-api.ts": ts_index("bff", BFF, bff_ops, ui_extra),
        ROOT / "ui/src/contracts/supported-guidance-topics.ts": topic_ts,
        ROOT / "bff/src/contracts/bff-api.ts": ts_index("bff", BFF, bff_ops),
        ROOT / "bff/src/contracts/core-api.ts": ts_index("core", CORE, core_ops),
        ROOT / "bff/src/contracts/supported-guidance-topics.ts": topic_ts,
        ROOT / "src/api/generated/__init__.py": '"""Generated API contract artifacts."""\n',
        ROOT / "src/api/generated/core_api_models.py": py_models,
        ROOT / "src/api/generated/validation.py": py_validation,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift: list[str] = []
    for path, content in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if drift:
        print("generated contract drift: " + ", ".join(drift))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
