#!/usr/bin/env python3
"""Generate small, deterministic runtime indexes from authoritative contracts."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
FEATURE = ROOT / "specs/003-develop-ui/contracts"
BFF = FEATURE / "bff-api-v1.openapi.yaml"
CORE = FEATURE / "core-api-v1.openapi.yaml"
CATALOG = FEATURE / "supported-guidance-topics-v1.yaml"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def operations(path: Path) -> list[dict[str, str]]:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    result: list[dict[str, str]] = []
    for route, path_item in document["paths"].items():
        for method, operation in path_item.items():
            if method.lower() in {"get", "put", "post", "delete", "patch"}:
                result.append({"operationId": operation["operationId"], "method": method.upper(), "path": route})
    return result


def _fastify_refs(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: (f"urn:contract:{item.rsplit('/', 1)[-1]}#" if key == "$ref" else _fastify_refs(item)) for key, item in value.items()}
    if isinstance(value, list):
        return [_fastify_refs(item) for item in value]
    return value


def fastify_schemas(path: Path) -> tuple[list[dict[str, Any]], dict[str, dict[str, Any]]]:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    components = [dict({"$id": f"urn:contract:{name}"}, **_fastify_refs(schema)) for name, schema in document.get("components", {}).get("schemas", {}).items()]
    component_parameters = document.get("components", {}).get("parameters", {})
    routes: dict[str, dict[str, Any]] = {}
    for _route, path_item in document["paths"].items():
        for method, operation in path_item.items():
            if method.lower() not in {"get", "put", "post", "delete", "patch"}:
                continue
            schema: dict[str, Any] = {}
            parameters = []
            for parameter in operation.get("parameters", []):
                reference = parameter.get("$ref") if isinstance(parameter, dict) else None
                if isinstance(reference, str) and reference.startswith("#/components/parameters/"):
                    parameter = component_parameters[reference.rsplit("/", 1)[-1]]
                parameters.append(parameter)
            for location, target in (("query", "querystring"), ("path", "params"), ("header", "headers")):
                selected = [parameter for parameter in parameters if parameter.get("in") == location]
                if selected:
                    def property_name(parameter: dict[str, Any]) -> str:
                        name = parameter["name"]
                        return name.lower() if location == "header" else name

                    schema[target] = {
                        "type": "object",
                        "properties": {property_name(parameter): _fastify_refs(parameter.get("schema", {})) for parameter in selected},
                        "required": [property_name(parameter) for parameter in selected if parameter.get("required")],
                    }
            body = operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema")
            if body:
                schema["body"] = _fastify_refs(body)
            responses = {}
            for status, response in operation.get("responses", {}).items():
                response_schema = response.get("content", {}).get("application/json", {}).get("schema") if isinstance(response, dict) else None
                if response_schema:
                    responses[status] = _fastify_refs(response_schema)
            if responses:
                schema["response"] = responses
            routes[operation["operationId"]] = schema
    return components, routes


def ts_index(name: str, source: Path, entries: list[dict[str, str]], extras: str = "", schemas: bool = False) -> str:
    constant = name.upper()
    encoded = json.dumps(entries, indent=2, ensure_ascii=False)
    generated = (
        "// Generated by scripts/ci/generate_contracts.py. Do not edit.\n"
        f'export const {constant}_CONTRACT_DIGEST = "{digest(source)}" as const;\n'
        f"export const {constant}_OPERATIONS = {encoded} as const;\n"
        f"export type {name.title().replace('_', '')}OperationId = typeof {constant}_OPERATIONS[number][\"operationId\"];\n"
        + extras
    )
    if schemas:
        components, routes = fastify_schemas(source)
        generated += f"export const {constant}_COMPONENT_SCHEMAS = {json.dumps(components, indent=2, ensure_ascii=False)} as const;\n"
        generated += f"export const {constant}_ROUTE_SCHEMAS = {json.dumps(routes, indent=2, ensure_ascii=False)} as const;\n"
    return generated


def generated_files() -> dict[Path, str]:
    bff_ops = operations(BFF)
    core_ops = operations(CORE)
    catalog = yaml.safe_load(CATALOG.read_text(encoding="utf-8"))
    topics = catalog["topics"]
    ui_extra = """

export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  code: string;
  detail?: string;
  correlationId?: string;
  errors?: Record<string, string[]>;
  retryable?: boolean;
  fieldErrors?: Array<{ field: string; messages: string[] }>;
}

export interface ProgressCheckInRequest {
  employeeProfileId?: string | null;
  roadmapId: string;
  notes?: string;
  completedSteps?: string[];
  completedMilestoneKeys?: string[];
  newGoals?: string[];
}

export interface ProgressMilestone {
  id: string;
  milestoneKey: string;
  ordinal: number;
  title: string;
  skillArea: string;
  experienceLevelFit: string;
  timeHorizon: "immediate" | "near_term" | "long_term";
  concreteNextAction: string;
  reasonItMatters: string;
  priority: number;
  completionState: "pending" | "in_progress" | "completed";
  supportingNotes: string[];
}

export interface ProgressRoadmap {
  id: string;
  employeeProfileId: string;
  previousRoadmapId?: string | null;
  goalSummary: string;
  currentFocus: string;
  milestones: ProgressMilestone[];
  status: "draft" | "active" | "revised" | "completed";
  assumptions: string[];
  clarifyingQuestionsAsked: number;
  createdAt: string;
  updatedAt: string;
}

export interface ProgressReview {
  revision: {
    priorRoadmap: ProgressRoadmap;
    updatedRoadmap: ProgressRoadmap;
    completedSteps: string[];
    normalizedMilestoneKeys: string[];
    newGoals: string[];
    summary: string;
    createdAt: string;
  };
  presentation: string;
  followUpPrompt: string;
  checkIn: {
    id: string;
    employeeProfileId: string;
    roadmapId: string;
    notes: string;
    completedSteps: string[];
    normalizedMilestoneKeys: string[];
    newGoals: string[];
    updatedRecommendations: ProgressMilestone[];
    createdAt: string;
  };
  roadmapId: string;
  currentStatus: string;
  gaps: string[];
  milestones: ProgressMilestone[];
  nextAction: {
    kind: "retry_material" | "resume_session" | "continue_milestone" | "review_roadmap";
    title: string;
    reason: string;
    target: string;
  };
}

export interface CapabilityMetadata {
  contractVersion: string;
  catalogVersion: string;
  status: "compatible" | "read_only";
  generatedAt: string;
  supportedContractVersions: string[];
  supportedMutations: string[];
}

export interface BrowserSession {
  authenticated: boolean;
  employee?: { displayName: string };
  idleExpiresAt?: string;
  absoluteExpiresAt?: string;
  csrfToken?: string;
}
"""
    topic_json = json.dumps(topics, indent=2, ensure_ascii=False)
    topic_ts = (
        "// Generated by scripts/ci/generate_contracts.py. Do not edit.\n"
        "export type GuidanceTopicState = \"active\" | \"unavailable\" | \"retired\";\n"
        f'export const GUIDANCE_CATALOG_VERSION = "{catalog["catalog_version"]}" as const;\n'
        f'export const GUIDANCE_CATALOG_DIGEST = "{digest(CATALOG)}" as const;\n'
        f"export const GUIDANCE_TOPICS = {topic_json} as const;\n"
        "export type GuidanceTopic = typeof GUIDANCE_TOPICS[number];\n"
    )
    py_models = (
        '"""Generated core OpenAPI operation inventory. Do not edit."""\n\n'
        f'CORE_CONTRACT_DIGEST = "{digest(CORE)}"\n'
        f"CORE_OPERATIONS = {repr(tuple(entry['operationId'] for entry in core_ops))}\n"
    )
    py_validation = '''"""Runtime operation-registration validation against generated inventory."""\n\nfrom .core_api_models import CORE_OPERATIONS\n\n\ndef validate_registered_operations(operation_ids: set[str]) -> None:\n    unknown = operation_ids - set(CORE_OPERATIONS)\n    if unknown:\n        raise RuntimeError(f"Unknown core operation registrations: {sorted(unknown)}")\n'''
    return {
        ROOT / "config/supported-guidance-topics-v1.yaml": CATALOG.read_text(encoding="utf-8"),
        ROOT / "ui/src/contracts/bff-api.ts": ts_index("bff", BFF, bff_ops, ui_extra),
        ROOT / "ui/src/contracts/supported-guidance-topics.ts": topic_ts,
        ROOT / "bff/src/contracts/bff-api.ts": ts_index("bff", BFF, bff_ops, schemas=True),
        ROOT / "bff/src/contracts/core-api.ts": ts_index("core", CORE, core_ops, schemas=True),
        ROOT / "bff/src/contracts/supported-guidance-topics.ts": topic_ts,
        ROOT / "src/api/generated/__init__.py": '"""Generated API contract artifacts."""\n',
        ROOT / "src/api/generated/core_api_models.py": py_models,
        ROOT / "src/api/generated/validation.py": py_validation,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift: list[str] = []
    for path, content in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if drift:
        print("generated contract drift: " + ", ".join(drift))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
