apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-revalidation
  annotations:
    azure.workload.identity/client-id: "${LAB_REVALIDATION_WORKLOAD_CLIENT_ID}"
automountServiceAccountToken: true
