// Generated by scripts/ci/generate_contracts.py. Do not edit.
export const BFF_CONTRACT_DIGEST = "68d4c6d0d344bc46a1bef5e1cd397cd04f9bde436cf50b3cb144bddf4891ee1a" as const;
export const BFF_OPERATIONS = [
  {
    "operationId": "getBffCapabilities",
    "method": "GET",
    "path": "/capabilities"
  },
  {
    "operationId": "getBrowserSession",
    "method": "GET",
    "path": "/session"
  },
  {
    "operationId": "beginLogin",
    "method": "GET",
    "path": "/auth/login"
  },
  {
    "operationId": "completeLogin",
    "method": "GET",
    "path": "/auth/callback"
  },
  {
    "operationId": "logout",
    "method": "POST",
    "path": "/auth/logout"
  },
  {
    "operationId": "listBrowserRoadmaps",
    "method": "GET",
    "path": "/roadmaps"
  },
  {
    "operationId": "createBrowserRoadmap",
    "method": "POST",
    "path": "/roadmaps"
  },
  {
    "operationId": "getBrowserRoadmap",
    "method": "GET",
    "path": "/roadmaps/{id}"
  },
  {
    "operationId": "createBrowserGuidance",
    "method": "POST",
    "path": "/guidance"
  },
  {
    "operationId": "createBrowserProgressCheckIn",
    "method": "POST",
    "path": "/progress/check-ins"
  },
  {
    "operationId": "getBrowserProgressReview",
    "method": "GET",
    "path": "/progress/reviews"
  },
  {
    "operationId": "listBrowserLearningSessions",
    "method": "GET",
    "path": "/learning-sessions"
  },
  {
    "operationId": "getBrowserLearningSession",
    "method": "GET",
    "path": "/learning-sessions/{id}"
  },
  {
    "operationId": "startBrowserLearningSession",
    "method": "POST",
    "path": "/learning-sessions/{id}/start"
  },
  {
    "operationId": "completeBrowserLearningStep",
    "method": "PUT",
    "path": "/learning-sessions/{id}/steps/{stepId}/completion"
  },
  {
    "operationId": "listBrowserReviewAttempts",
    "method": "GET",
    "path": "/learning-sessions/{id}/review-attempts"
  },
  {
    "operationId": "createBrowserReviewAttempt",
    "method": "POST",
    "path": "/learning-sessions/{id}/review-attempts"
  },
  {
    "operationId": "getBrowserReviewAttempt",
    "method": "GET",
    "path": "/review-attempts/{id}"
  },
  {
    "operationId": "answerBrowserReviewQuestion",
    "method": "PUT",
    "path": "/review-attempts/{id}/answers/{questionId}"
  },
  {
    "operationId": "submitBrowserReviewAttempt",
    "method": "POST",
    "path": "/review-attempts/{id}/submit"
  },
  {
    "operationId": "reportBrowserLabReference",
    "method": "POST",
    "path": "/lab-references/{id}/reports"
  },
  {
    "operationId": "getBrowserNextLearningAction",
    "method": "GET",
    "path": "/learning/next-action"
  }
] as const;
export type BffOperationId = typeof BFF_OPERATIONS[number]["operationId"];
