// Generated by scripts/ci/generate_contracts.py. Do not edit.
export const CORE_CONTRACT_DIGEST = "74eb81eed70e24183862bd187ab9f9bfa778d2992efeae54b397e2d36df19497" as const;
export const CORE_OPERATIONS = [
  {
    "operationId": "getCoreCapabilities",
    "method": "GET",
    "path": "/capabilities"
  },
  {
    "operationId": "bootstrapEmployeeSession",
    "method": "POST",
    "path": "/identity/session-bootstrap"
  },
  {
    "operationId": "listRoadmaps",
    "method": "GET",
    "path": "/roadmaps"
  },
  {
    "operationId": "createRoadmap",
    "method": "POST",
    "path": "/roadmaps"
  },
  {
    "operationId": "getRoadmap",
    "method": "GET",
    "path": "/roadmaps/{roadmap_id}"
  },
  {
    "operationId": "createGuidance",
    "method": "POST",
    "path": "/guidance"
  },
  {
    "operationId": "createProgressCheckIn",
    "method": "POST",
    "path": "/progress/check-ins"
  },
  {
    "operationId": "getProgressReview",
    "method": "GET",
    "path": "/progress/reviews"
  },
  {
    "operationId": "listLearningSessions",
    "method": "GET",
    "path": "/learning-sessions"
  },
  {
    "operationId": "startLearningSession",
    "method": "POST",
    "path": "/learning-sessions/{session_id}/start"
  },
  {
    "operationId": "getLearningSession",
    "method": "GET",
    "path": "/learning-sessions/{session_id}"
  },
  {
    "operationId": "completeLearningStep",
    "method": "PUT",
    "path": "/learning-sessions/{session_id}/steps/{step_id}/completion"
  },
  {
    "operationId": "listReviewAttempts",
    "method": "GET",
    "path": "/learning-sessions/{session_id}/review-attempts"
  },
  {
    "operationId": "createReviewAttempt",
    "method": "POST",
    "path": "/learning-sessions/{session_id}/review-attempts"
  },
  {
    "operationId": "getReviewAttempt",
    "method": "GET",
    "path": "/review-attempts/{attempt_id}"
  },
  {
    "operationId": "answerReviewQuestion",
    "method": "PUT",
    "path": "/review-attempts/{attempt_id}/answers/{question_id}"
  },
  {
    "operationId": "submitReviewAttempt",
    "method": "POST",
    "path": "/review-attempts/{attempt_id}/submit"
  },
  {
    "operationId": "reportLabReference",
    "method": "POST",
    "path": "/lab-references/{lab_reference_id}/reports"
  },
  {
    "operationId": "getNextLearningAction",
    "method": "GET",
    "path": "/learning/next-action"
  }
] as const;
export type CoreOperationId = typeof CORE_OPERATIONS[number]["operationId"];
export const CORE_COMPONENT_SCHEMAS = [
  {
    "$id": "urn:contract:CoreCapabilities",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "contract_version",
      "accepted_bff_range",
      "api_schema_version",
      "guidance_topic_catalog_version",
      "enabled_features"
    ],
    "properties": {
      "contract_version": {
        "type": "string"
      },
      "accepted_bff_range": {
        "type": "string"
      },
      "api_schema_version": {
        "type": "string",
        "const": "1.0.0"
      },
      "guidance_topic_catalog_version": {
        "type": "string",
        "const": "1.0.0"
      },
      "enabled_features": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  {
    "$id": "urn:contract:SessionEligibility",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "eligible",
      "employee_subject",
      "lifecycle_state"
    ],
    "properties": {
      "eligible": {
        "type": "boolean",
        "const": true
      },
      "employee_subject": {
        "type": "string"
      },
      "lifecycle_state": {
        "type": "string",
        "const": "active"
      }
    }
  },
  {
    "$id": "urn:contract:EmployeeProfileInput",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "role",
      "experience_level",
      "target_role",
      "available_time_per_week"
    ],
    "properties": {
      "id": {
        "type": "string",
        "description": "Compatibility identifier; never grants employee authority."
      },
      "role": {
        "type": "string",
        "minLength": 1
      },
      "experience_level": {
        "type": "string",
        "enum": [
          "unknown",
          "beginner",
          "intermediate",
          "advanced",
          "lead"
        ]
      },
      "target_role": {
        "type": "string",
        "minLength": 1
      },
      "target_specializations": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        }
      },
      "available_time_per_week": {
        "type": "integer",
        "minimum": 0
      },
      "learning_preferences": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        }
      },
      "constraints": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        }
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      }
    }
  },
  {
    "$id": "urn:contract:RoadmapCreateRequest",
    "type": "object",
    "additionalProperties": false,
    "description": "Owner is derived from authorization: delegated calls create an employee-owned roadmap and app-role calls create an application-owned roadmap for the validated MachinePrincipal. No request field selects it.",
    "required": [
      "employee_profile"
    ],
    "properties": {
      "employee_profile": {
        "$ref": "urn:contract:EmployeeProfileInput#"
      },
      "request_text": {
        "type": [
          "string",
          "null"
        ]
      },
      "clarifying_questions_asked": {
        "type": "integer",
        "minimum": 0,
        "default": 0
      }
    }
  },
  {
    "$id": "urn:contract:GuidanceRequest",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "topic",
      "employee_profile"
    ],
    "properties": {
      "topic": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128,
        "description": "Active ID or alias from supported-guidance-topics-v1.yaml."
      },
      "employee_profile": {
        "$ref": "urn:contract:EmployeeProfileInput#"
      },
      "request_text": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  {
    "$id": "urn:contract:ProgressCheckInRequest",
    "type": "object",
    "additionalProperties": false,
    "description": "Delegated calls may reference only the employee's roadmap; app-role calls may reference only a roadmap owned by the same validated MachinePrincipal.",
    "required": [
      "roadmap_id"
    ],
    "properties": {
      "employee_profile_id": {
        "type": [
          "string",
          "null"
        ],
        "deprecated": true,
        "description": "Compatibility-only hint; never grants employee authority."
      },
      "roadmap_id": {
        "type": "string",
        "minLength": 1
      },
      "notes": {
        "type": "string",
        "default": ""
      },
      "completed_steps": {
        "type": "array",
        "description": "Backward-compatible legacy milestone title or skill-area references. Existing trim/case-insensitive all-matches behavior is preserved; an unknown value is retained but changes no milestone.",
        "items": {
          "type": "string",
          "minLength": 1
        }
      },
      "completed_milestone_keys": {
        "type": "array",
        "description": "Preferred unambiguous stable milestone keys. Every supplied key must exist in the actor-owned roadmap or the request returns 422.",
        "items": {
          "type": "string",
          "pattern": "^[a-z0-9][a-z0-9._-]{2,127}$"
        }
      },
      "new_goals": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  },
  {
    "$id": "urn:contract:RoadmapResult",
    "oneOf": [
      {
        "$ref": "urn:contract:ReadyRoadmapResult#"
      },
      {
        "$ref": "urn:contract:NeedsMoreInfoRoadmapResult#"
      }
    ],
    "discriminator": {
      "propertyName": "status",
      "mapping": {
        "ready": "#/components/schemas/ReadyRoadmapResult",
        "needs_more_info": "#/components/schemas/NeedsMoreInfoRoadmapResult"
      }
    }
  },
  {
    "$id": "urn:contract:ReadyRoadmapResult",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "status",
      "roadmap_id",
      "employee_profile_id",
      "roadmap",
      "clarifying_questions",
      "assumptions",
      "presentation",
      "follow_up_prompt"
    ],
    "properties": {
      "status": {
        "type": "string",
        "const": "ready"
      },
      "roadmap_id": {
        "type": "string",
        "minLength": 1
      },
      "employee_profile_id": {
        "type": "string",
        "minLength": 1
      },
      "roadmap": {
        "$ref": "urn:contract:CareerRoadmap#"
      },
      "clarifying_questions": {
        "type": "array",
        "maxItems": 0,
        "items": {
          "$ref": "urn:contract:ClarifyingQuestion#"
        }
      },
      "assumptions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "presentation": {
        "type": "string"
      },
      "follow_up_prompt": {
        "type": "string"
      }
    }
  },
  {
    "$id": "urn:contract:NeedsMoreInfoRoadmapResult",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "status",
      "roadmap_id",
      "employee_profile_id",
      "roadmap",
      "clarifying_questions",
      "assumptions",
      "presentation",
      "follow_up_prompt"
    ],
    "properties": {
      "status": {
        "type": "string",
        "const": "needs_more_info"
      },
      "roadmap_id": {
        "type": "null"
      },
      "employee_profile_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "roadmap": {
        "type": "null"
      },
      "clarifying_questions": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "urn:contract:ClarifyingQuestion#"
        }
      },
      "assumptions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "presentation": {
        "type": "string"
      },
      "follow_up_prompt": {
        "type": "string"
      }
    }
  },
  {
    "$id": "urn:contract:GuidanceResult",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "requested_topic",
      "supported",
      "topic_summary",
      "current_level_fit",
      "practical_next_action",
      "common_pitfalls",
      "related_topics",
      "suggestions",
      "notes"
    ],
    "properties": {
      "requested_topic": {
        "type": "string"
      },
      "resolved_topic": {
        "type": "string"
      },
      "supported": {
        "type": "boolean",
        "const": true
      },
      "topic_summary": {
        "type": "string"
      },
      "current_level_fit": {
        "type": "string"
      },
      "practical_next_action": {
        "type": "string"
      },
      "lab_references": {
        "type": "array",
        "items": {
          "$ref": "urn:contract:LabReference#"
        }
      },
      "suggestions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "common_pitfalls": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "related_topics": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "notes": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  {
    "$id": "urn:contract:LearningSession",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "roadmap_id",
      "content_version",
      "question_version",
      "lab_reference_versions",
      "title",
      "objective",
      "estimated_minutes",
      "status",
      "current_step_ordinal",
      "steps",
      "retirement"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "roadmap_id": {
        "type": "string"
      },
      "content_version": {
        "type": "string"
      },
      "question_version": {
        "type": "string"
      },
      "lab_reference_versions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "title": {
        "type": "string"
      },
      "objective": {
        "type": "string"
      },
      "estimated_minutes": {
        "type": "integer",
        "minimum": 20,
        "maximum": 30
      },
      "status": {
        "type": "string",
        "enum": [
          "not_started",
          "in_progress",
          "retry_required",
          "completed"
        ]
      },
      "current_step_ordinal": {
        "type": "integer",
        "minimum": 0
      },
      "steps": {
        "type": "array",
        "items": {
          "$ref": "urn:contract:LearningStep#"
        }
      },
      "retirement": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "status",
          "security_critical"
        ],
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "draft",
              "published",
              "retired"
            ]
          },
          "security_critical": {
            "type": "boolean"
          },
          "resume_until": {
            "type": [
              "string",
              "null"
            ],
            "format": "date-time"
          },
          "replacement_content_id": {
            "type": [
              "string",
              "null"
            ]
          },
          "replacement_content_version": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    }
  },
  {
    "$id": "urn:contract:ReviewAttempt",
    "oneOf": [
      {
        "$ref": "urn:contract:InProgressReviewAttempt#"
      },
      {
        "$ref": "urn:contract:SubmittedReviewAttempt#"
      }
    ],
    "discriminator": {
      "propertyName": "status",
      "mapping": {
        "in_progress": "#/components/schemas/InProgressReviewAttempt",
        "submitted": "#/components/schemas/SubmittedReviewAttempt"
      }
    }
  },
  {
    "$id": "urn:contract:InProgressReviewAttempt",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "attempt_number",
      "question_snapshot_version",
      "status",
      "questions",
      "answers",
      "started_at",
      "score_percent",
      "passed",
      "submitted_at"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "attempt_number": {
        "type": "integer",
        "minimum": 1
      },
      "question_snapshot_version": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "const": "in_progress"
      },
      "questions": {
        "type": "array",
        "minItems": 3,
        "maxItems": 5,
        "items": {
          "$ref": "urn:contract:ReviewQuestion#"
        }
      },
      "answers": {
        "type": "array",
        "items": {
          "$ref": "urn:contract:PersistedReviewAnswer#"
        }
      },
      "started_at": {
        "type": "string",
        "format": "date-time"
      },
      "score_percent": {
        "type": "null"
      },
      "passed": {
        "type": "null"
      },
      "submitted_at": {
        "type": "null"
      },
      "latest": {
        "type": "boolean"
      },
      "highest": {
        "type": "boolean"
      }
    }
  },
  {
    "$id": "urn:contract:SubmittedReviewAttempt",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "attempt_number",
      "question_snapshot_version",
      "status",
      "questions",
      "answers",
      "started_at",
      "score_percent",
      "passed",
      "submitted_at"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "attempt_number": {
        "type": "integer",
        "minimum": 1
      },
      "question_snapshot_version": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "const": "submitted"
      },
      "questions": {
        "type": "array",
        "minItems": 3,
        "maxItems": 5,
        "items": {
          "$ref": "urn:contract:ReviewQuestion#"
        }
      },
      "answers": {
        "type": "array",
        "minItems": 3,
        "maxItems": 5,
        "items": {
          "$ref": "urn:contract:PersistedReviewAnswer#"
        }
      },
      "started_at": {
        "type": "string",
        "format": "date-time"
      },
      "score_percent": {
        "type": "number",
        "minimum": 0,
        "maximum": 100
      },
      "passed": {
        "type": "boolean"
      },
      "submitted_at": {
        "type": "string",
        "format": "date-time"
      },
      "latest": {
        "type": "boolean"
      },
      "highest": {
        "type": "boolean"
      }
    }
  },
  {
    "$id": "urn:contract:ReviewAnswerRequest",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "answer_key"
    ],
    "properties": {
      "answer_key": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  {
    "$id": "urn:contract:ReviewAnswerFeedback",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "question_id",
      "submitted_answer_key",
      "correct",
      "explanation",
      "answered_at"
    ],
    "properties": {
      "question_id": {
        "type": "string"
      },
      "submitted_answer_key": {
        "type": "string"
      },
      "correct": {
        "type": "boolean"
      },
      "explanation": {
        "type": "string",
        "minLength": 1
      },
      "answered_at": {
        "type": "string",
        "format": "date-time"
      }
    }
  },
  {
    "$id": "urn:contract:PersistedReviewAnswer",
    "type": "object",
    "additionalProperties": false,
    "description": "Safe restoration DTO. It contains the employee's submitted choice and feedback for that answered question, never the authoritative correct answer key for any unanswered question.",
    "required": [
      "question_id",
      "submitted_answer_key",
      "correct",
      "explanation",
      "answered_at"
    ],
    "properties": {
      "question_id": {
        "type": "string"
      },
      "submitted_answer_key": {
        "type": "string"
      },
      "correct": {
        "type": "boolean"
      },
      "explanation": {
        "type": "string",
        "minLength": 1
      },
      "answered_at": {
        "type": "string",
        "format": "date-time"
      }
    }
  },
  {
    "$id": "urn:contract:ReviewResult",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "attempt_id",
      "score_percent",
      "passed",
      "session_status",
      "missed_question_ids",
      "next_action"
    ],
    "properties": {
      "attempt_id": {
        "type": "string"
      },
      "score_percent": {
        "type": "number",
        "minimum": 0,
        "maximum": 100
      },
      "passed": {
        "type": "boolean"
      },
      "session_status": {
        "type": "string",
        "enum": [
          "retry_required",
          "completed"
        ]
      },
      "missed_question_ids": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "next_action": {
        "$ref": "urn:contract:NextAction#"
      }
    }
  },
  {
    "$id": "urn:contract:ProgressReview",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "revision",
      "presentation",
      "follow_up_prompt",
      "roadmap_id",
      "current_status",
      "gaps",
      "milestones",
      "next_action"
    ],
    "properties": {
      "revision": {
        "$ref": "urn:contract:RoadmapRevision#"
      },
      "presentation": {
        "type": "string"
      },
      "follow_up_prompt": {
        "type": "string"
      },
      "check_in": {
        "description": "Non-null for every newly persisted owner-scoped review. Null is retained only for legacy nonpersisted machine-response compatibility.",
        "oneOf": [
          {
            "$ref": "urn:contract:ProgressCheckIn#"
          },
          {
            "type": "null"
          }
        ]
      },
      "roadmap_id": {
        "type": "string"
      },
      "current_status": {
        "type": "string"
      },
      "gaps": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "milestones": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "urn:contract:RoadmapMilestone#"
        }
      },
      "next_action": {
        "$ref": "urn:contract:NextAction#"
      }
    }
  },
  {
    "$id": "urn:contract:NextAction",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "kind",
      "title",
      "reason",
      "target"
    ],
    "properties": {
      "kind": {
        "type": "string",
        "enum": [
          "retry_material",
          "resume_session",
          "continue_milestone",
          "review_roadmap"
        ]
      },
      "title": {
        "type": "string",
        "minLength": 1
      },
      "reason": {
        "type": "string",
        "minLength": 1
      },
      "target": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  {
    "$id": "urn:contract:ClarifyingQuestion",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "prompt",
      "why_it_matters"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "prompt": {
        "type": "string",
        "minLength": 1
      },
      "why_it_matters": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  {
    "$id": "urn:contract:RoadmapMilestone",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "title",
      "skill_area",
      "experience_level_fit",
      "time_horizon",
      "concrete_next_action",
      "reason_it_matters",
      "priority",
      "completion_state",
      "supporting_notes"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "milestone_key": {
        "type": "string",
        "description": "Stable additive identifier. Required on newly persisted owned roadmaps; optional only when reading a legacy v1 roadmap."
      },
      "ordinal": {
        "type": "integer",
        "minimum": 0,
        "description": "Stable ordering value. Required on newly persisted owned roadmaps; optional only when reading a legacy v1 roadmap."
      },
      "title": {
        "type": "string",
        "minLength": 1
      },
      "skill_area": {
        "type": "string",
        "minLength": 1
      },
      "experience_level_fit": {
        "type": "string"
      },
      "time_horizon": {
        "type": "string",
        "enum": [
          "immediate",
          "near_term",
          "long_term"
        ]
      },
      "concrete_next_action": {
        "type": "string",
        "minLength": 1
      },
      "reason_it_matters": {
        "type": "string"
      },
      "completion_state": {
        "type": "string",
        "enum": [
          "pending",
          "in_progress",
          "completed"
        ]
      },
      "priority": {
        "type": "integer"
      },
      "supporting_notes": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  {
    "$id": "urn:contract:CareerRoadmap",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "employee_profile_id",
      "goal_summary",
      "current_focus",
      "milestones",
      "next_actions",
      "status",
      "assumptions",
      "clarifying_questions_asked",
      "created_at",
      "updated_at"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "owner_type": {
        "type": "string",
        "enum": [
          "employee",
          "application"
        ],
        "description": "Additive audit/ownership class; no employee or machine principal ID is exposed. May be absent only on a legacy v1 record."
      },
      "employee_profile_id": {
        "type": "string",
        "description": "Record relationship only; authorization uses token claims."
      },
      "previous_roadmap_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "goal_summary": {
        "type": "string",
        "minLength": 1
      },
      "current_focus": {
        "type": "string",
        "minLength": 1
      },
      "milestones": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "urn:contract:RoadmapMilestone#"
        }
      },
      "next_actions": {
        "type": "array",
        "deprecated": true,
        "description": "Legacy machine-consumer candidate list retained for v1 compatibility; BFF/UI must ignore it and use exactly one NextAction selected by core.",
        "items": {
          "$ref": "urn:contract:RoadmapMilestone#"
        }
      },
      "status": {
        "type": "string",
        "enum": [
          "draft",
          "active",
          "revised",
          "completed"
        ]
      },
      "assumptions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "clarifying_questions_asked": {
        "type": "integer",
        "minimum": 0
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      }
    }
  },
  {
    "$id": "urn:contract:OwnedRoadmapMilestone",
    "allOf": [
      {
        "$ref": "urn:contract:RoadmapMilestone#"
      },
      {
        "type": "object",
        "required": [
          "milestone_key",
          "ordinal"
        ]
      }
    ]
  },
  {
    "$id": "urn:contract:OwnedCareerRoadmap",
    "description": "Enriched employee-owned roadmap required on delegated BFF calls. Legacy records that cannot be deterministically backfilled return LEGACY_RECORD_NOT_UI_COMPATIBLE instead of a partial 200 response.",
    "allOf": [
      {
        "$ref": "urn:contract:CareerRoadmap#"
      },
      {
        "type": "object",
        "required": [
          "owner_type",
          "milestones"
        ],
        "properties": {
          "owner_type": {
            "type": "string",
            "const": "employee"
          },
          "milestones": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "urn:contract:OwnedRoadmapMilestone#"
            }
          }
        }
      }
    ]
  },
  {
    "$id": "urn:contract:OwnedRoadmapResult",
    "oneOf": [
      {
        "$ref": "urn:contract:OwnedReadyRoadmapResult#"
      },
      {
        "$ref": "urn:contract:NeedsMoreInfoRoadmapResult#"
      }
    ],
    "discriminator": {
      "propertyName": "status",
      "mapping": {
        "ready": "#/components/schemas/OwnedReadyRoadmapResult",
        "needs_more_info": "#/components/schemas/NeedsMoreInfoRoadmapResult"
      }
    }
  },
  {
    "$id": "urn:contract:OwnedReadyRoadmapResult",
    "allOf": [
      {
        "$ref": "urn:contract:ReadyRoadmapResult#"
      },
      {
        "type": "object",
        "properties": {
          "roadmap": {
            "$ref": "urn:contract:OwnedCareerRoadmap#"
          }
        }
      }
    ]
  },
  {
    "$id": "urn:contract:PersistedRoadmapRevision",
    "allOf": [
      {
        "$ref": "urn:contract:RoadmapRevision#"
      },
      {
        "type": "object",
        "required": [
          "normalized_milestone_keys"
        ],
        "properties": {
          "prior_roadmap": {
            "$ref": "urn:contract:OwnedCareerRoadmap#"
          },
          "updated_roadmap": {
            "$ref": "urn:contract:OwnedCareerRoadmap#"
          }
        }
      }
    ]
  },
  {
    "$id": "urn:contract:PersistedProgressCheckIn",
    "allOf": [
      {
        "$ref": "urn:contract:ProgressCheckIn#"
      },
      {
        "type": "object",
        "required": [
          "owner_type",
          "normalized_milestone_keys"
        ],
        "properties": {
          "owner_type": {
            "type": "string",
            "const": "employee"
          }
        }
      }
    ]
  },
  {
    "$id": "urn:contract:PersistedProgressReview",
    "description": "Enriched employee-owned review required on delegated BFF calls.",
    "allOf": [
      {
        "$ref": "urn:contract:ProgressReview#"
      },
      {
        "type": "object",
        "required": [
          "check_in"
        ],
        "properties": {
          "revision": {
            "$ref": "urn:contract:PersistedRoadmapRevision#"
          },
          "check_in": {
            "$ref": "urn:contract:PersistedProgressCheckIn#"
          },
          "milestones": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "urn:contract:OwnedRoadmapMilestone#"
            }
          }
        }
      }
    ]
  },
  {
    "$id": "urn:contract:LearningStep",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "ordinal",
      "step_type",
      "title",
      "status"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "ordinal": {
        "type": "integer",
        "minimum": 0
      },
      "step_type": {
        "type": "string",
        "enum": [
          "reading",
          "activity",
          "lab",
          "review"
        ]
      },
      "title": {
        "type": "string",
        "minLength": 1
      },
      "status": {
        "type": "string",
        "enum": [
          "pending",
          "completed"
        ]
      },
      "lab_reference": {
        "oneOf": [
          {
            "$ref": "urn:contract:LabReference#"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  {
    "$id": "urn:contract:ReviewQuestion",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "ordinal",
      "prompt",
      "choices"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "ordinal": {
        "type": "integer",
        "minimum": 0
      },
      "prompt": {
        "type": "string",
        "minLength": 1
      },
      "choices": {
        "type": "object",
        "minProperties": 2,
        "additionalProperties": {
          "type": "string"
        },
        "description": "Choice keys and display text; correct keys are excluded."
      }
    }
  },
  {
    "$id": "urn:contract:RoadmapRevision",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "prior_roadmap",
      "updated_roadmap",
      "completed_steps",
      "new_goals",
      "summary",
      "created_at"
    ],
    "properties": {
      "prior_roadmap": {
        "$ref": "urn:contract:CareerRoadmap#"
      },
      "updated_roadmap": {
        "$ref": "urn:contract:CareerRoadmap#"
      },
      "completed_steps": {
        "type": "array",
        "description": "Original compatibility references supplied by the actor.",
        "items": {
          "type": "string"
        }
      },
      "normalized_milestone_keys": {
        "type": "array",
        "description": "Stable keys resolved from completed_steps for new records.",
        "items": {
          "type": "string"
        }
      },
      "new_goals": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "summary": {
        "type": "string"
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      }
    }
  },
  {
    "$id": "urn:contract:ProgressCheckIn",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "employee_profile_id",
      "roadmap_id",
      "notes",
      "completed_steps",
      "new_goals",
      "updated_recommendations",
      "created_at"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "owner_type": {
        "type": "string",
        "enum": [
          "employee",
          "application"
        ],
        "description": "Additive actor class. The actual owner identifier remains internal."
      },
      "employee_profile_id": {
        "type": "string"
      },
      "roadmap_id": {
        "type": "string"
      },
      "notes": {
        "type": "string"
      },
      "completed_steps": {
        "type": "array",
        "description": "Original compatibility references supplied by the actor.",
        "items": {
          "type": "string"
        }
      },
      "normalized_milestone_keys": {
        "type": "array",
        "description": "Stable milestone keys resolved by core for new records.",
        "items": {
          "type": "string"
        }
      },
      "new_goals": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "updated_recommendations": {
        "type": "array",
        "items": {
          "$ref": "urn:contract:RoadmapMilestone#"
        }
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      }
    }
  },
  {
    "$id": "urn:contract:LabReference",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "provider",
      "objective",
      "prerequisites",
      "estimated_minutes",
      "cost_status",
      "availability_status",
      "destination_url"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "provider": {
        "type": "string"
      },
      "objective": {
        "type": "string"
      },
      "prerequisites": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "estimated_minutes": {
        "type": "integer",
        "minimum": 1
      },
      "cost_status": {
        "type": "string",
        "enum": [
          "free",
          "paid",
          "subscription",
          "unknown"
        ]
      },
      "availability_status": {
        "type": "string",
        "enum": [
          "active",
          "unavailable",
          "retired"
        ]
      },
      "destination_url": {
        "type": "string",
        "format": "uri",
        "pattern": "^https://"
      }
    }
  },
  {
    "$id": "urn:contract:LabReportRequest",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "reason"
    ],
    "properties": {
      "reason": {
        "type": "string",
        "enum": [
          "unavailable",
          "unsuitable",
          "cost_mismatch",
          "other"
        ]
      },
      "comment": {
        "type": [
          "string",
          "null"
        ],
        "maxLength": 1000
      }
    }
  },
  {
    "$id": "urn:contract:ProblemDetails",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "title",
      "status",
      "code",
      "correlation_id"
    ],
    "properties": {
      "type": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "status": {
        "type": "integer"
      },
      "code": {
        "type": "string"
      },
      "detail": {
        "type": [
          "string",
          "null"
        ]
      },
      "field_errors": {
        "type": "object",
        "additionalProperties": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "retryable": {
        "type": "boolean"
      },
      "correlation_id": {
        "type": "string"
      }
    }
  }
] as const;
export const CORE_ROUTE_SCHEMAS = {
  "getCoreCapabilities": {
    "response": {
      "200": {
        "$ref": "urn:contract:CoreCapabilities#"
      }
    }
  },
  "bootstrapEmployeeSession": {
    "response": {
      "200": {
        "$ref": "urn:contract:SessionEligibility#"
      }
    }
  },
  "listRoadmaps": {
    "response": {
      "200": {
        "type": "array",
        "items": {
          "$ref": "urn:contract:CareerRoadmap#"
        }
      }
    }
  },
  "createRoadmap": {
    "body": {
      "$ref": "urn:contract:RoadmapCreateRequest#"
    },
    "response": {
      "200": {
        "$ref": "urn:contract:RoadmapResult#"
      }
    }
  },
  "getRoadmap": {
    "params": {
      "type": "object",
      "properties": {
        "roadmap_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "roadmap_id"
      ]
    },
    "response": {
      "200": {
        "$ref": "urn:contract:CareerRoadmap#"
      }
    }
  },
  "createGuidance": {
    "body": {
      "$ref": "urn:contract:GuidanceRequest#"
    },
    "response": {
      "200": {
        "$ref": "urn:contract:GuidanceResult#"
      }
    }
  },
  "createProgressCheckIn": {
    "body": {
      "$ref": "urn:contract:ProgressCheckInRequest#"
    },
    "response": {
      "200": {
        "$ref": "urn:contract:ProgressReview#"
      }
    }
  },
  "getProgressReview": {
    "querystring": {
      "type": "object",
      "properties": {
        "roadmap_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "roadmap_id"
      ]
    },
    "response": {
      "200": {
        "$ref": "urn:contract:ProgressReview#"
      }
    }
  },
  "listLearningSessions": {
    "querystring": {
      "type": "object",
      "properties": {
        "roadmap_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "roadmap_id"
      ]
    },
    "response": {
      "200": {
        "type": "array",
        "items": {
          "$ref": "urn:contract:LearningSession#"
        }
      }
    }
  },
  "startLearningSession": {
    "response": {
      "200": {
        "$ref": "urn:contract:LearningSession#"
      }
    }
  },
  "getLearningSession": {
    "response": {
      "200": {
        "$ref": "urn:contract:LearningSession#"
      }
    }
  },
  "completeLearningStep": {
    "params": {
      "type": "object",
      "properties": {
        "step_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "step_id"
      ]
    },
    "response": {
      "200": {
        "$ref": "urn:contract:LearningSession#"
      }
    }
  },
  "listReviewAttempts": {
    "response": {
      "200": {
        "type": "array",
        "items": {
          "$ref": "urn:contract:ReviewAttempt#"
        }
      }
    }
  },
  "createReviewAttempt": {
    "response": {
      "200": {
        "$ref": "urn:contract:ReviewAttempt#"
      }
    }
  },
  "getReviewAttempt": {
    "params": {
      "type": "object",
      "properties": {
        "attempt_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "attempt_id"
      ]
    },
    "response": {
      "200": {
        "$ref": "urn:contract:ReviewAttempt#"
      }
    }
  },
  "answerReviewQuestion": {
    "params": {
      "type": "object",
      "properties": {
        "attempt_id": {
          "type": "string",
          "minLength": 1
        },
        "question_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "attempt_id",
        "question_id"
      ]
    },
    "body": {
      "$ref": "urn:contract:ReviewAnswerRequest#"
    },
    "response": {
      "200": {
        "$ref": "urn:contract:ReviewAnswerFeedback#"
      }
    }
  },
  "submitReviewAttempt": {
    "params": {
      "type": "object",
      "properties": {
        "attempt_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "attempt_id"
      ]
    },
    "response": {
      "200": {
        "$ref": "urn:contract:ReviewResult#"
      }
    }
  },
  "reportLabReference": {
    "params": {
      "type": "object",
      "properties": {
        "lab_reference_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "lab_reference_id"
      ]
    },
    "body": {
      "$ref": "urn:contract:LabReportRequest#"
    }
  },
  "getNextLearningAction": {
    "querystring": {
      "type": "object",
      "properties": {
        "roadmap_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "roadmap_id"
      ]
    },
    "response": {
      "200": {
        "$ref": "urn:contract:NextAction#"
      }
    }
  }
} as const;
