// Generated by scripts/ci/generate_contracts.py. Do not edit.
export const CORE_CONTRACT_DIGEST = "8364b04aa1be5a7a486e39d436eba7fbecdcc96ef86482d784436a3ea317946b" as const;
export const CORE_OPERATIONS = [
  {
    "operationId": "getCoreCapabilities",
    "method": "GET",
    "path": "/capabilities"
  },
  {
    "operationId": "bootstrapEmployeeSession",
    "method": "POST",
    "path": "/identity/session-bootstrap"
  },
  {
    "operationId": "listRoadmaps",
    "method": "GET",
    "path": "/roadmaps"
  },
  {
    "operationId": "createRoadmap",
    "method": "POST",
    "path": "/roadmaps"
  },
  {
    "operationId": "getRoadmap",
    "method": "GET",
    "path": "/roadmaps/{roadmap_id}"
  },
  {
    "operationId": "createGuidance",
    "method": "POST",
    "path": "/guidance"
  },
  {
    "operationId": "createProgressCheckIn",
    "method": "POST",
    "path": "/progress/check-ins"
  },
  {
    "operationId": "getProgressReview",
    "method": "GET",
    "path": "/progress/reviews"
  },
  {
    "operationId": "listLearningSessions",
    "method": "GET",
    "path": "/learning-sessions"
  },
  {
    "operationId": "startLearningSession",
    "method": "POST",
    "path": "/learning-sessions/{session_id}/start"
  },
  {
    "operationId": "getLearningSession",
    "method": "GET",
    "path": "/learning-sessions/{session_id}"
  },
  {
    "operationId": "completeLearningStep",
    "method": "PUT",
    "path": "/learning-sessions/{session_id}/steps/{step_id}/completion"
  },
  {
    "operationId": "listReviewAttempts",
    "method": "GET",
    "path": "/learning-sessions/{session_id}/review-attempts"
  },
  {
    "operationId": "createReviewAttempt",
    "method": "POST",
    "path": "/learning-sessions/{session_id}/review-attempts"
  },
  {
    "operationId": "getReviewAttempt",
    "method": "GET",
    "path": "/review-attempts/{attempt_id}"
  },
  {
    "operationId": "answerReviewQuestion",
    "method": "PUT",
    "path": "/review-attempts/{attempt_id}/answers/{question_id}"
  },
  {
    "operationId": "submitReviewAttempt",
    "method": "POST",
    "path": "/review-attempts/{attempt_id}/submit"
  },
  {
    "operationId": "reportLabReference",
    "method": "POST",
    "path": "/lab-references/{lab_reference_id}/reports"
  },
  {
    "operationId": "getNextLearningAction",
    "method": "GET",
    "path": "/learning/next-action"
  }
] as const;
export type CoreOperationId = typeof CORE_OPERATIONS[number]["operationId"];
