import { createContext, useCallback, useContext, useMemo, useReducer, type PropsWithChildren } from "react";
import type { Conversation, LearnerState, Message, UiError } from "../contracts/learner-state";
import { authenticationEpoch } from "./auth-epoch";

type Action = { type: "draft"; value: string } | { type: "pending"; message: Message } | { type: "delivered"; message: Message } | { type: "failed"; error: UiError } | { type: "snapshot"; snapshot: Pick<LearnerState, "roadmap" | "milestones" | "currentTopic" | "nextAction" | "status" | "error" | "lastUpdatedAt"> } | { type: "reset" } | { type: "invalidate" };
const initialConversation: Conversation = { messages: [], draft: "", deliveryState: "ready", failure: null };
export const initialLearnerState: LearnerState = { roadmap: null, conversation: initialConversation, currentTopic: null, nextAction: null, milestones: [], lastUpdatedAt: null, status: "loading", error: null, authEpoch: authenticationEpoch.capture() };
export function learnerStateReducer(state: LearnerState, action: Action): LearnerState { switch (action.type) { case "draft": return { ...state, conversation: { ...state.conversation, draft: action.value } }; case "pending": return { ...state, conversation: { ...state.conversation, messages: [...state.conversation.messages, action.message], deliveryState: "pending", failure: null } }; case "delivered": return { ...state, conversation: { ...state.conversation, messages: [...state.conversation.messages, action.message], draft: "", deliveryState: "delivered", failure: null } }; case "failed": return { ...state, conversation: { ...state.conversation, deliveryState: "failed", failure: action.error } }; case "snapshot": return { ...state, ...action.snapshot }; case "reset": return { ...state, conversation: initialConversation }; case "invalidate": return { ...initialLearnerState, authEpoch: authenticationEpoch.capture() }; default: return state; } }
interface LearnerContextValue { state: LearnerState; dispatch: React.Dispatch<Action>; invalidate: () => void; resetConversation: () => void; }
const LearnerContext = createContext<LearnerContextValue | null>(null);
export function LearnerStateProvider({ children }: PropsWithChildren) { const [state, dispatch] = useReducer(learnerStateReducer, initialLearnerState); const invalidate = useCallback(() => dispatch({ type: "invalidate" }), []); const resetConversation = useCallback(() => dispatch({ type: "reset" }), []); const value = useMemo(() => ({ state, dispatch, invalidate, resetConversation }), [state, invalidate, resetConversation]); return <LearnerContext.Provider value={value}>{children}</LearnerContext.Provider>; }
export function useLearnerState() { const value = useContext(LearnerContext); if (!value) throw new Error("LearnerStateProvider is required"); return value; }
