namespace: devops-career-agent-nonprod
resources:
  - namespace.yaml
  - ../../base
  - configmap.yaml
  - gateway.yaml
  - httproute.yaml
  - private-machine-service.yaml
  - platform-digests.yaml
patches:
  - path: machine-tls-secret-provider-class.yaml
images:
  - name: devops-career-agent
    newName: acrdevopscareernonprod.azurecr.io/devops-career-agent
    digest: sha256:c388547f83eb7e3c0494055eaebe568a2480cea667387dc7012142296fdc0a1b
