apiVersion: v1
kind: Namespace
metadata:
  name: devops-career-agent-nonprod
  labels:
    app.kubernetes.io/name: devops-career-agent
    app.kubernetes.io/part-of: devops-career-agent
    environment: nonprod
