apiVersion: v1
kind: Service
metadata:
  name: core-private-machine
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "${PRIVATE_CORE_LOAD_BALANCER_IP}"
    external-dns.alpha.kubernetes.io/hostname: "core.${PRIVATE_CORE_DNS_ZONE_NAME}"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges: ["${PRIVATE_MACHINE_SOURCE_CIDR}"]
  selector: {app.kubernetes.io/name: core}
  ports:
    - {name: https, port: 8443, targetPort: https}
